"""Governance Application Layer.

包含 arch_guard, hitl, suggestion, core, hooks 等应用层组件。
"""

from .arch_guard import (
    ArchGuardConfig,
    ArchGuardEngine,
    GuardAction,
    GuardFinding,
    GuardPolicy,
    GuardReport,
    GuardRule,
    GuardSeverity,
    GovernanceReportAdapter,
)
from .core import (
    GovernanceFacade,
    GovernanceRunner,
    append_history_snapshot,
    create_governance_facade,
    list_history_entries,
    persist_planning_report,
    persist_report,
    run_governance_check_and_persist,
    run_planning_gate_sync,
    run_review_gate_sync,
)
from .hitl import (
    HitlCorrection,
    HitlDecision,
    HitlDecisionRecord,
    HitlEventType,
    HitlFacade,
    HitlGate,
    HitlPolicyResult,
    HitlReplayDirective,
    HitlRequestRecord,
    HitlRiskLevel,
    HitlService,
    HitlSession,
    HitlSessionStatus,
    apply_after_sprint_decision,
    apply_before_sprint_decision,
    build_hitl_context,
    build_replay_context,
    create_hitl_coordinator,
    create_hitl_facade,
    default_hitl_db_path,
    evaluate_hitl_policy,
    hitl_gate_enabled,
    is_hitl_enabled,
    merge_correction_into_context,
    normalize_hitl_decision,
    normalize_hitl_decision_with_intent,
    parse_hitl_gates,
    summarize_context_diff,
    summarize_hitl_context,
    transition_session_status,
    validate_hitl_decision_for_submit,
    validate_session_transition,
    decision_to_terminal_status,
    get_hitl_timeout_seconds,
)
from .hooks import GovernanceSprintHooks, GovernanceTaskLifecycleHooks
from .suggestion import (
    Suggestion,
    SuggestionAnalyzer,
    SuggestionApprovalRecord,
    SuggestionFacade,
    SuggestionImpactScope,
    SuggestionOverviewResult,
    SuggestionReviewContext,
    SuggestionReviewRecord,
    SuggestionSeverity,
    SuggestionSourceType,
    SuggestionStatus,
    create_suggestion_facade,
)

__all__ = [
    # arch_guard
    "ArchGuardConfig",
    "ArchGuardEngine",
    "GuardAction",
    "GuardFinding",
    "GuardPolicy",
    "GuardReport",
    "GuardRule",
    "GuardSeverity",
    "GovernanceReportAdapter",
    # core
    "GovernanceFacade",
    "GovernanceRunner",
    "append_history_snapshot",
    "create_governance_facade",
    "list_history_entries",
    "persist_planning_report",
    "persist_report",
    "run_governance_check_and_persist",
    "run_planning_gate_sync",
    "run_review_gate_sync",
    # hitl
    "HitlCorrection",
    "HitlDecision",
    "HitlDecisionRecord",
    "HitlEventType",
    "HitlFacade",
    "HitlGate",
    "HitlPolicyResult",
    "HitlReplayDirective",
    "HitlRequestRecord",
    "HitlRiskLevel",
    "HitlService",
    "HitlSession",
    "HitlSessionStatus",
    "apply_after_sprint_decision",
    "apply_before_sprint_decision",
    "build_hitl_context",
    "build_replay_context",
    "create_hitl_coordinator",
    "create_hitl_facade",
    "default_hitl_db_path",
    "evaluate_hitl_policy",
    "hitl_gate_enabled",
    "is_hitl_enabled",
    "merge_correction_into_context",
    "normalize_hitl_decision",
    "normalize_hitl_decision_with_intent",
    "parse_hitl_gates",
    "summarize_context_diff",
    "summarize_hitl_context",
    "transition_session_status",
    "validate_hitl_decision_for_submit",
    "validate_session_transition",
    "decision_to_terminal_status",
    "get_hitl_timeout_seconds",
    # hooks
    "GovernanceSprintHooks",
    "GovernanceTaskLifecycleHooks",
    # suggestion
    "Suggestion",
    "SuggestionAnalyzer",
    "SuggestionApprovalRecord",
    "SuggestionFacade",
    "SuggestionImpactScope",
    "SuggestionOverviewResult",
    "SuggestionReviewContext",
    "SuggestionReviewRecord",
    "SuggestionSeverity",
    "SuggestionSourceType",
    "SuggestionStatus",
    "create_suggestion_facade",
]
