"""领域层 - 按照 DDD 洋葱结构划分子域"""

from . import core
from . import supporting
from . import generic

from .generic.errors.exceptions import (
    Severity,
    SprintCycleError,
    ConfigError,
    ExecutionError,
    DiagnosticError,
    ReleasePlanError,
    EvolutionError,
    LLMError,
)

from .generic.interfaces.hooks import (
    EXECUTION_START,
    EXECUTION_STARTED_EVENT,
    EXECUTION_START_FAILED_EVENT,
    HOOK_ACTIONS,
    HOOK_EVENTS,
    GOVERNANCE_CHECK,
    GOVERNANCE_CHECKED_EVENT,
    GOVERNANCE_CHECK_FAILED_EVENT,
    HookContext,
    HookDefinition,
    HookHandler,
    HookPhase,
    HookPolicy,
    HookRegistry,
    HookResult,
    HookRunner,
    SUGGESTION_APPROVE_SUGGESTION,
    SUGGESTION_APPROVAL_COMPLETED_EVENT,
    SUGGESTION_APPROVED_EVENT,
    SUGGESTION_ARCHIVE,
    SUGGESTION_ARCHIVED_EVENT,
    SUGGESTION_ATTACH_REPLAY,
    SUGGESTION_CAPTURE_EXECUTION_EVENT,
    SUGGESTION_CAPTURED_FROM_EXECUTION_EVENT,
    SUGGESTION_PROMOTE_TO_HITL,
    SUGGESTION_PROMOTED_TO_HITL_EVENT,
    SUGGESTION_REJECT_SUGGESTION,
    SUGGESTION_REJECTION_COMPLETED_EVENT,
    SUGGESTION_REJECTED_EVENT,
    SUGGESTION_REVIEW,
    SUGGESTION_REVIEWED_EVENT,
    SUGGESTION_REVIEW_RECORD_EVENT,
    hook_action,
    hook_events,
)

__all__ = [
    "core",
    "supporting",
    "generic",
    # exceptions
    "Severity",
    "SprintCycleError",
    "ConfigError",
    "ExecutionError",
    "DiagnosticError",
    "ReleasePlanError",
    "EvolutionError",
    "LLMError",
    # hooks
    "EXECUTION_START",
    "EXECUTION_STARTED_EVENT",
    "EXECUTION_START_FAILED_EVENT",
    "HOOK_ACTIONS",
    "HOOK_EVENTS",
    "GOVERNANCE_CHECK",
    "GOVERNANCE_CHECKED_EVENT",
    "GOVERNANCE_CHECK_FAILED_EVENT",
    "HookContext",
    "HookDefinition",
    "HookHandler",
    "HookPhase",
    "HookPolicy",
    "HookRegistry",
    "HookResult",
    "HookRunner",
    "SUGGESTION_APPROVE_SUGGESTION",
    "SUGGESTION_APPROVAL_COMPLETED_EVENT",
    "SUGGESTION_APPROVED_EVENT",
    "SUGGESTION_ARCHIVE",
    "SUGGESTION_ARCHIVED_EVENT",
    "SUGGESTION_ATTACH_REPLAY",
    "SUGGESTION_CAPTURE_EXECUTION_EVENT",
    "SUGGESTION_CAPTURED_FROM_EXECUTION_EVENT",
    "SUGGESTION_PROMOTE_TO_HITL",
    "SUGGESTION_PROMOTED_TO_HITL_EVENT",
    "SUGGESTION_REJECT_SUGGESTION",
    "SUGGESTION_REJECTION_COMPLETED_EVENT",
    "SUGGESTION_REJECTED_EVENT",
    "SUGGESTION_REVIEW",
    "SUGGESTION_REVIEWED_EVENT",
    "SUGGESTION_REVIEW_RECORD_EVENT",
    "hook_action",
    "hook_events",
]
