"""
Coder Agent 执行器 - 负责代码编写
"""

import asyncio
import logging
import re
from typing import Dict, Any
from .base import AgentExecutor, AgentContext, AgentResult, AgentType

logger = logging.getLogger(__name__)


class CoderAgent(AgentExecutor):
    """Coder Agent 执行器 - 负责代码编写任务"""
    
    @property
    def agent_type(self) -> AgentType:
        return AgentType.CODER
    
    async def _do_execute(self, task: str, context: AgentContext) -> AgentResult:
        """执行代码编写任务"""
        logger.info(f"📝 Coder 执行: {task[:50]}...")
        
        # 解析需求
        requirements = self._parse_requirements(task, context)
        
        # 生成代码
        code_result = await self._generate_code(requirements, context)
        
        # 验证代码
        is_valid, validation_msg = self._validate_code(code_result["code"])
        
        # 分析质量
        quality_metrics = self._analyze_quality(code_result["code"], context)
        
        # 生成反馈
        feedback = self._generate_feedback(quality_metrics, context)
        
        result = AgentResult(
            success=is_valid,
            output=code_result["summary"],
            artifacts={
                "code": code_result["code"],
                "files": code_result.get("files", []),
                "language": context.config.get("language", "python"),
                "requirements": requirements,
            },
            metrics={
                "lines": code_result.get("lines", 0),
                "complexity": quality_metrics.get("complexity", 0),
                "quality_score": quality_metrics.get("quality_score", 0),
            },
            feedback=feedback,
        )
        
        if not is_valid:
            result.error = validation_msg
        
        return result
    
    def _parse_requirements(self, task: str, context: AgentContext) -> Dict[str, Any]:
        """解析任务需求"""
        return {
            "task": task,
            "language": context.config.get("language", "python"),
            "framework": context.config.get("framework", ""),
            "goals": context.project_goals,
            "dependencies": list(context.dependencies.keys()),
        }
    
    async def _generate_code(self, requirements: Dict[str, Any], context: AgentContext) -> Dict[str, Any]:
        """生成代码"""
        language = requirements.get("language", "python")
        task_name = requirements["task"].split()[0].lower()
        
        if language == "python":
            code = f'''"""
{requirements["task"]}
Generated by SprintCycle CoderAgent
"""

class {task_name.title()}:
    """根据需求: {requirements["task"]}"""
    
    def __init__(self):
        self.data = None
    
    def execute(self) -> dict:
        """执行主要逻辑"""
        return {{"status": "success", "data": self.data}}
    
    def validate(self) -> bool:
        """验证数据"""
        return self.data is not None
'''
        else:
            code = f"-- {requirements['task']}\n-- Generated by SprintCycle"
        
        return {
            "code": code,
            "summary": f"已生成 {language} 代码: {requirements['task'][:30]}...",
            "files": [f"generated/{task_name}.py"],
            "lines": len(code.split("\n")),
        }
    
    def _validate_code(self, code: str) -> tuple[bool, str]:
        """验证代码"""
        if not code or len(code.strip()) < 10:
            return False, "代码太短或为空"
        if code.count("{") != code.count("}"):
            return False, "括号不匹配"
        if code.count("(") != code.count(")"):
            return False, "圆括号不匹配"
        return True, "代码验证通过"
    
    def _analyze_quality(self, code: str, context: AgentContext) -> Dict[str, Any]:
        """分析代码质量"""
        lines = code.split("\n")
        non_empty_lines = [l for l in lines if l.strip()]
        avg_line_length = sum(len(l) for l in non_empty_lines) / max(len(non_empty_lines), 1) if non_empty_lines else 0
        max_indent = max((len(l) - len(l.lstrip())) for l in lines if l.strip()) if lines else 0
        complexity = max_indent // 4 + 1
        has_docstring = '"""' in code or "'''" in code or "/**" in code
        
        return {
            "lines": len(lines),
            "avg_line_length": round(avg_line_length, 1),
            "complexity": complexity,
            "has_documentation": has_docstring,
            "quality_score": self._calculate_quality_score(code, context),
        }
    
    def _calculate_quality_score(self, code: str, context: AgentContext) -> float:
        """计算质量分数"""
        score = 70.0
        if context.feedback_history:
            last_feedback = context.feedback_history[-1].lower()
            if "excellent" in last_feedback or "优秀" in last_feedback:
                score += 15
            elif "good" in last_feedback or "良好" in last_feedback:
                score += 5
            elif "improve" in last_feedback or "改进" in last_feedback:
                score -= 5
        if '"""' in code or "'''" in code:
            score += 5
        if "raise" in code or "except" in code:
            score += 5
        return min(max(score, 0), 100)
    
    def _generate_feedback(self, quality_metrics: Dict[str, Any], context: AgentContext) -> str:
        """生成反馈"""
        feedback_parts = []
        lines = quality_metrics.get("lines", 0)
        if lines > 200:
            feedback_parts.append(f"代码规模较大({lines}行)")
        elif lines > 50:
            feedback_parts.append(f"代码规模适中({lines}行)")
        else:
            feedback_parts.append(f"代码简洁({lines}行)")
        
        complexity = quality_metrics.get("complexity", 1)
        if complexity > 3:
            feedback_parts.append(f"复杂度较高({complexity})")
        else:
            feedback_parts.append("结构清晰")
        
        quality = quality_metrics.get("quality_score", 0)
        if quality >= 85:
            feedback_parts.append("整体质量优秀")
        elif quality >= 70:
            feedback_parts.append("整体质量良好")
        else:
            feedback_parts.append("需要进一步优化")
        
        feedback = f"[Coder反馈] {'; '.join(feedback_parts)}"
        if context.feedback_history and len(context.feedback_history) > 1:
            feedback += "。前次反馈已考虑。"
        return feedback


__all__ = ["CoderAgent"]
