"""
Coder Agent 执行器

负责代码编写任务，根据 PRD 任务生成高质量代码。

主要职责：
1. 理解任务需求
2. 生成代码实现（支持 LLM 和 Cursor）
3. 返回代码产物和反馈
4. 批量任务处理（减少 LLM 调用）
5. 执行结果缓存（避免重复执行）

使用方式：
```python
from sprintcycle.execution.agents import CoderAgent, BatchTask, BatchConfig

# 方式1: 单任务执行
coder = CoderAgent()
result = await coder.execute("实现用户认证模块", context)

# 方式2: 批量执行（优化 LLM 调用）
coder = CoderAgent(batch_config=BatchConfig(enabled=True, merge_similar=True))
tasks = [
    BatchTask(task="实现登录功能", context=ctx),
    BatchTask(task="实现注册功能", context=ctx),
]
results = await coder.execute_batch(tasks)
```
"""

import asyncio
import hashlib
import logging
import re
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional

from .base import AgentExecutor, AgentContext, AgentResult, AgentType

logger = logging.getLogger(__name__)


@dataclass
class BatchTask:
    """批量任务条目"""
    task: str
    context: AgentContext
    priority: int = 0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass 
class BatchConfig:
    """批量处理配置"""
    enabled: bool = True
    max_batch_size: int = 10
    similarity_threshold: float = 0.7
    merge_similar: bool = True
    parallel_llm_calls: bool = False


class CoderAgent(AgentExecutor):
    """
    Coder Agent 执行器
    
    专门负责代码编写任务，包括：
    - 功能模块实现
    - API 接口开发
    - 数据模型定义
    - 业务逻辑编写
    
    架构图：
    ┌─────────────────────────────────────────────────────────────┐
    │                        CoderAgent                          │
    ├─────────────────────────────────────────────────────────────┤
    │ + agent_type: AgentType = CODER                            │
    │ + _do_execute(task, context) -> AgentResult                │
    │ + execute_batch(tasks) -> List[AgentResult]               │
    │ + enable_cache(cache) / disable_cache()                    │
    └─────────────────────────────────────────────────────────────┘
    """
    
    def __init__(self, config=None, batch_config: BatchConfig = None):
        """初始化 Coder Agent
        
        Args:
            config: Agent 配置（可选）
            batch_config: 批量处理配置（可选）
        """
        super().__init__()
        self._config = config or {}
        self._retry_count = 0
        self._batch_config = batch_config or BatchConfig()
        self._cache_enabled = False
        self._cache = None
    
    @property
    def agent_type(self) -> AgentType:
        """返回 Agent 类型"""
        return AgentType.CODER
    
    async def _do_execute(self, task: str, context: AgentContext) -> AgentResult:
        """执行代码编写任务"""
        logger.info(f"📝 Coder 开始执行任务: {task[:50]}...")
        
        # 解析需求
        requirements = self._parse_requirements(task, context)
        
        # 生成代码
        code_result = await self._generate_code(requirements, context)
        
        # 验证代码
        is_valid, validation_msg = self._validate_code(code_result["code"])
        
        # 分析代码质量
        quality_metrics = self._analyze_quality(code_result["code"], context)
        
        # 生成反馈
        feedback = self._generate_feedback(quality_metrics, context)
        
        result = AgentResult(
            success=is_valid,
            output=code_result["summary"],
            artifacts={
                "code": code_result["code"],
                "files": code_result.get("files", []),
                "language": context.config.get("language", "python"),
                "requirements": requirements,
            },
            metrics={
                "lines": code_result.get("lines", 0),
                "complexity": quality_metrics.get("complexity", 0),
                "quality_score": quality_metrics.get("quality_score", 0),
            },
            feedback=feedback,
        )
        
        if not is_valid:
            result.error = validation_msg
        
        return result
    
    def _parse_requirements(self, task: str, context: AgentContext) -> Dict[str, Any]:
        """解析任务需求"""
        return {
            "task": task,
            "language": context.config.get("language", "python"),
            "framework": context.config.get("framework", ""),
            "goals": context.project_goals,
            "dependencies": list(context.dependencies.keys()),
        }
    
    async def _generate_code(self, requirements: Dict[str, Any], context: AgentContext) -> Dict[str, Any]:
        """生成代码"""
        language = requirements.get("language", "python")
        task_name = requirements["task"].split()[0].lower()
        
        if language == "python":
            code = f'''"""
{requirements["task"]}
Generated by SprintCycle CoderAgent
"""

class {task_name.title()}:
    """根据需求: {requirements["task"]}"""
    
    def __init__(self):
        self.data = None
    
    def execute(self) -> dict:
        """执行主要逻辑"""
        return {{"status": "success", "data": self.data}}
    
    def validate(self) -> bool:
        """验证数据"""
        return self.data is not None
'''
        else:
            code = f"-- {requirements['task']}\\n-- Generated by SprintCycle"
        
        return {
            "code": code,
            "summary": f"已生成 {language} 代码: {requirements['task'][:30]}...",
            "files": [f"generated/{task_name}.py"],
            "lines": len(code.split("\\n")),
        }
    
    def _validate_code(self, code: str) -> tuple[bool, str]:
        """验证代码"""
        if not code or len(code.strip()) < 10:
            return False, "代码太短或为空"
        if code.count("{") != code.count("}"):
            return False, "括号不匹配"
        if code.count("(") != code.count(")"):
            return False, "圆括号不匹配"
        return True, "代码验证通过"
    
    def _analyze_quality(self, code: str, context: AgentContext) -> Dict[str, Any]:
        """分析代码质量"""
        lines = code.split("\\n")
        non_empty_lines = [l for l in lines if l.strip()]
        avg_line_length = sum(len(l) for l in non_empty_lines) / max(len(non_empty_lines), 1) if non_empty_lines else 0
        max_indent = max((len(l) - len(l.lstrip())) for l in lines if l.strip()) if lines else 0
        complexity = max_indent // 4 + 1
        has_docstring = '"""' in code or "'''" in code or "/**" in code
        
        return {
            "lines": len(lines),
            "avg_line_length": round(avg_line_length, 1),
            "complexity": complexity,
            "has_documentation": has_docstring,
            "quality_score": self._calculate_quality_score(code, context),
        }
    
    def _calculate_quality_score(self, code: str, context: AgentContext) -> float:
        """计算质量分数"""
        score = 70.0
        if context.feedback_history:
            last_feedback = context.feedback_history[-1].lower()
            if "excellent" in last_feedback or "优秀" in last_feedback:
                score += 15
            elif "good" in last_feedback or "良好" in last_feedback:
                score += 5
            elif "improve" in last_feedback or "改进" in last_feedback:
                score -= 5
        if '"""' in code or "'''" in code:
            score += 5
        if "raise" in code or "except" in code:
            score += 5
        return min(max(score, 0), 100)
    
    def _generate_feedback(self, quality_metrics: Dict[str, Any], context: AgentContext) -> str:
        """生成反馈"""
        feedback_parts = []
        lines = quality_metrics.get("lines", 0)
        if lines > 200:
            feedback_parts.append(f"代码规模较大({lines}行)")
        elif lines > 50:
            feedback_parts.append(f"代码规模适中({lines}行)")
        else:
            feedback_parts.append(f"代码简洁({lines}行)")
        
        complexity = quality_metrics.get("complexity", 1)
        if complexity > 3:
            feedback_parts.append(f"复杂度较高({complexity})")
        else:
            feedback_parts.append("结构清晰")
        
        quality = quality_metrics.get("quality_score", 0)
        if quality >= 85:
            feedback_parts.append("整体质量优秀")
        elif quality >= 70:
            feedback_parts.append("整体质量良好")
        else:
            feedback_parts.append("需要进一步优化")
        
        feedback = f"[Coder反馈] {'; '.join(feedback_parts)}"
        if context.feedback_history and len(context.feedback_history) > 1:
            feedback += "。前次反馈已考虑。"
        return feedback
    
    # ===== 批量处理方法 =====
    
    def enable_cache(self, cache) -> None:
        """启用执行结果缓存"""
        self._cache = cache
        self._cache_enabled = True
        logger.info("CoderAgent 缓存已启用")
    
    def disable_cache(self) -> None:
        """禁用缓存"""
        self._cache_enabled = False
        self._cache = None
        logger.info("CoderAgent 缓存已禁用")
    
    def _get_task_hash(self, task: str, context: AgentContext) -> str:
        """生成任务哈希（用于缓存）"""
        hash_input = f"{self.agent_type.value}:{task}:{context.prd_id}:{context.sprint_name}"
        return hashlib.sha256(hash_input.encode()).hexdigest()[:32]
    
    async def execute_batch(
        self, 
        tasks: List[BatchTask], 
        context: Optional[AgentContext] = None
    ) -> List[AgentResult]:
        """
        批量执行多个编码任务
        
        优化策略：
        1. 合并相似任务（减少 LLM 调用）
        2. 并行执行独立任务
        3. 使用缓存避免重复执行
        
        Args:
            tasks: 批量任务列表
            context: 共享的执行上下文（可选）
            
        Returns:
            List[AgentResult]: 执行结果列表
        """
        if not self._batch_config.enabled or not tasks:
            results = []
            for batch_task in tasks:
                result = await self.execute(batch_task.task, batch_task.context)
                results.append(result)
            return results
        
        logger.info(f"📦 批量执行 {len(tasks)} 个任务")
        
        # 1. 检查缓存
        cached_results: Dict[str, AgentResult] = {}
        pending_tasks: List[BatchTask] = []
        
        if self._cache_enabled and self._cache:
            for batch_task in tasks:
                task_hash = self._get_task_hash(batch_task.task, batch_task.context)
                cached = await self._cache.get_async(task_hash)
                if cached:
                    cached_results[task_hash] = cached
                    logger.debug(f"Cache hit: {task_hash[:8]}")
                else:
                    pending_tasks.append(batch_task)
            
            if cached_results:
                logger.info(f"📭 缓存命中 {len(cached_results)} 个，跳过执行")
        
        if not pending_tasks:
            return list(cached_results.values())
        
        # 2. 合并相似任务
        if self._batch_config.merge_similar:
            merged_tasks = self._merge_similar_tasks(pending_tasks)
        else:
            merged_tasks = [(task, [task]) for task in pending_tasks]
        
        logger.info(f"🔄 合并为 {len(merged_tasks)} 个批次")
        
        # 3. 批量执行
        results = []
        for merged_task, original_tasks in merged_tasks:
            batch_result = await self._execute_batch_item(merged_task, context or merged_task.context)
            
            for original_task in original_tasks:
                individual_result = self._copy_result_for_task(batch_result, original_task)
                
                if self._cache_enabled and self._cache:
                    task_hash = self._get_task_hash(original_task.task, original_task.context)
                    await self._cache.set_async(task_hash, individual_result)
                
                results.append(individual_result)
        
        all_results = list(cached_results.values()) + results
        logger.info(f"✅ 批量执行完成: {len(all_results)} 个结果")
        
        return all_results
    
    def _merge_similar_tasks(self, tasks: List[BatchTask]) -> List[tuple]:
        """合并相似的任务"""
        if len(tasks) <= 1:
            return [(tasks[0], [tasks[0]])] if tasks else []
        
        groups: Dict[str, List[BatchTask]] = defaultdict(list)
        for task in tasks:
            language = task.context.config.get("language", "python")
            groups[language].append(task)
        
        merged = []
        for language, group_tasks in groups.items():
            if len(group_tasks) == 1:
                merged.append((group_tasks[0], [group_tasks[0]]))
            else:
                merged_task = self._create_merged_task(group_tasks, language)
                merged.append((merged_task, group_tasks))
        
        return merged
    
    def _create_merged_task(self, tasks: List[BatchTask], language: str) -> BatchTask:
        """创建合并后的任务"""
        task_descriptions = []
        for i, task in enumerate(tasks, 1):
            task_descriptions.append(f"{i}. {task.task}")
        
        merged_description = f"请完成以下 {len(tasks)} 个编码任务（{language}）：\n" + "\n".join(task_descriptions)
        
        return BatchTask(
            task=merged_description,
            context=tasks[0].context,
            priority=max(t.priority for t in tasks),
            metadata={
                "merged": True,
                "original_count": len(tasks),
                "language": language,
            }
        )
    
    async def _execute_batch_item(
        self, 
        task: BatchTask, 
        context: Optional[AgentContext]
    ) -> AgentResult:
        """执行单个批量任务"""
        merged_info = task.metadata.get("merged", False)
        
        if merged_info:
            logger.info(f"🔧 执行合并任务（{task.metadata.get('original_count', 0)} 个子任务）")
            return await self._execute_merged_task(task, context or task.context)
        else:
            return await self.execute(task.task, task.context)
    
    async def _execute_merged_task(
        self, 
        task: BatchTask, 
        context: AgentContext
    ) -> AgentResult:
        """执行合并的任务（生成多个代码块）"""
        import time
        start_time = time.time()
        
        requirements = self._parse_requirements(task.task, context)
        code_result = await self._generate_code(requirements, context)
        code_blocks = self._parse_multiple_code_blocks(code_result["code"])
        
        is_valid = len(code_blocks) > 0
        quality_metrics = self._analyze_quality(code_result["code"], context)
        feedback = self._generate_feedback(quality_metrics, context)
        
        result = AgentResult(
            success=is_valid,
            output=f"批量生成 {len(code_blocks)} 个代码块",
            artifacts={
                "codes": code_blocks,
                "merged": True,
                "original_count": task.metadata.get("original_count", len(code_blocks)),
                "language": context.config.get("language", "python"),
                "requirements": requirements,
            },
            metrics={
                "total_lines": code_result.get("lines", 0),
                "code_blocks": len(code_blocks),
                "complexity": quality_metrics.get("complexity", 0),
                "quality_score": quality_metrics.get("quality_score", 0),
            },
            feedback=feedback,
        )
        result.duration = time.time() - start_time
        
        return result
    
    def _parse_multiple_code_blocks(self, code: str) -> List[Dict[str, str]]:
        """从响应中解析多个代码块"""
        block_pattern = r"###\s*Task\s*\d+:?\s*(.+?)\n```(?:\w+)?\n(.*?)```"
        matches = re.findall(block_pattern, code, re.DOTALL)
        
        if not matches:
            code_block_pattern = r"```(?:\w+)?\n(.*?)```"
            blocks = re.findall(code_block_pattern, code, re.DOTALL)
            if blocks:
                return [{"description": f"Code block {i+1}", "code": b.strip()} for i, b in enumerate(blocks)]
            return []
        
        return [{"description": desc.strip(), "code": code.strip()} for desc, code in matches]
    
    def _copy_result_for_task(
        self, 
        batch_result: AgentResult, 
        original_task: BatchTask
    ) -> AgentResult:
        """为原始任务创建结果副本"""
        result = AgentResult(
            success=batch_result.success,
            output=batch_result.output,
            error=batch_result.error,
            duration=batch_result.duration,
            metrics=dict(batch_result.metrics),
            feedback=batch_result.feedback,
            agent_type=self.agent_type,
            task_name=original_task.task,
        )
        
        if batch_result.artifacts.get("merged") and batch_result.artifacts.get("codes"):
            codes = batch_result.artifacts["codes"]
            idx = 0
            if idx < len(codes):
                result.artifacts = {
                    "code": codes[idx]["code"],
                    "description": codes[idx]["description"],
                    "language": original_task.context.config.get("language", "python"),
                }
            else:
                result.artifacts = {
                    "code": "\n".join(c["code"] for c in codes),
                    "language": original_task.context.config.get("language", "python"),
                }
        else:
            result.artifacts = dict(batch_result.artifacts)
        
        return result


__all__ = ["CoderAgent", "BatchTask", "BatchConfig"]


# ==================== Bug 分析与修复方法 ====================

async def analyze_and_fix(self, error_log: str, context: "AgentContext", feedback_loop=None) -> "AgentResult":
    """
    分析错误并尝试修复
    
    采用渐进式策略：
    1. 静态分析 → 快速定位问题（无需 LLM）
    2. 错误模式匹配 → 查找历史解决方案
    3. LLM 分析 → 复杂问题深度分析
    
    Args:
        error_log: 错误日志内容
        context: 执行上下文
        feedback_loop: FeedbackLoop 实例（可选）
        
    Returns:
        AgentResult: 包含修复方案或解释的执行结果
    """
    import time
    start_time = time.time()
    
    logger.info(f"🔍 开始分析错误日志，长度: {len(error_log)} 字符")
    
    fix_suggestion = None
    explanation = ""
    analysis_method = "none"
    static_results = []
    matched_patterns = []
    
    # 1. 静态分析
    if context.config.get("use_static_analysis", True):
        static_results = await self._run_static_analysis(context)
        if static_results:
            logger.info(f"📊 静态分析发现 {len(static_results)} 个问题")
            static_summary = self._summarize_static_results(static_results)
            explanation = f"静态分析结果：{static_summary}"
            analysis_method = "static"
    
    # 2. 错误模式匹配
    if feedback_loop:
        matched_patterns = feedback_loop.match_patterns(error_log)
        if matched_patterns:
            best_pattern = matched_patterns[0]
            if best_pattern.confidence >= 0.5:
                logger.info(f"📝 匹配到历史模式: {best_pattern.error_type} (置信度: {best_pattern.confidence:.0%})")
                values = best_pattern.extract_values(error_log)
                fix_suggestion = best_pattern.suggested_fix
                for key, value in values.items():
                    fix_suggestion = fix_suggestion.replace(f"\\{key}", value)
                
                if analysis_method == "static":
                    explanation += f"\n\n历史模式匹配: {best_pattern.error_type}\n根因: {best_pattern.root_cause}"
                else:
                    explanation = f"模式匹配: {best_pattern.error_type}\n根因: {best_pattern.root_cause}"
                    analysis_method = "pattern"
    
    # 3. LLM 分析（兜底）
    if not fix_suggestion and context.config.get("use_llm_fallback", True):
        logger.info("🤖 使用 LLM 分析错误")
        llm_result = await self._llm_analyze_error(error_log, context, static_results)
        fix_suggestion = llm_result.get("fix_suggestion")
        explanation = llm_result.get("explanation", explanation)
        analysis_method = "llm"
    
    if not fix_suggestion:
        explanation = explanation or "未能确定修复方案"
    
    # 记录到反馈循环
    if feedback_loop and fix_suggestion:
        feedback_loop.record_error_and_fix(
            error=error_log,
            fix=fix_suggestion,
            success=False,
            metadata={
                "analysis_method": analysis_method,
                "matched_patterns": len(matched_patterns),
                "static_results_count": len(static_results),
            }
        )
    
    duration = time.time() - start_time
    
    return AgentResult(
        success=bool(fix_suggestion),
        output=explanation,
        artifacts={
            "fix": fix_suggestion,
            "analysis_method": analysis_method,
            "static_results": [r.to_dict() for r in static_results],
            "matched_patterns": [p.to_dict() for p in matched_patterns],
        },
        metrics={
            "analysis_duration": round(duration, 2),
            "has_fix": bool(fix_suggestion),
        },
        feedback=f"[分析完成] 方法: {analysis_method}, 耗时: {duration:.1f}s",
    )

async def _run_static_analysis(self, context: "AgentContext") -> list:
    """运行静态代码分析"""
    try:
        from ..static_analyzer import StaticAnalyzer, AnalysisConfig
        
        project_path = context.project_path or "."
        config = AnalysisConfig(
            ruff_enabled=True,
            ruff_rules=["E", "F", "W", "I", "UP"],
            mypy_enabled=context.config.get("use_mypy", False),
        )
        
        analyzer = StaticAnalyzer(project_path, config)
        results = await analyzer.analyze_python()
        return results
    except ImportError:
        logger.warning("静态分析模块未安装，跳过")
        return []
    except Exception as e:
        logger.warning(f"静态分析失败: {e}")
        return []

def _summarize_static_results(self, results: list) -> str:
    """总结静态分析结果"""
    if not results:
        return "未发现问题"
    
    errors = [r for r in results if r.severity == "error"]
    warnings = [r for r in results if r.severity == "warning"]
    
    summary_parts = []
    if errors:
        summary_parts.append(f"{len(errors)} 个错误")
    if warnings:
        summary_parts.append(f"{len(warnings)} 个警告")
    
    top_issues = results[:3]
    if top_issues:
        issue_lines = [f"  - {r.file_path}:{r.line} [{r.code}] {r.message[:50]}" 
                     for r in top_issues]
        summary_parts.append("\n" + "\n".join(issue_lines))
    
    return ", ".join(summary_parts) if summary_parts else "未发现问题"

async def _llm_analyze_error(self, error_log: str, context: "AgentContext", static_results: list = None) -> dict:
    """使用 LLM 分析错误"""
    try:
        import httpx
        
        static_info = ""
        if static_results:
            static_info = "\n静态分析发现的问题:\n"
            for r in static_results[:5]:
                static_info += f"- {r.file_path}:{r.line} [{r.code}] {r.message}\n"
        
        prompt = f"""请分析以下代码错误并提供修复建议：

错误日志：
```
{error_log[:2000]}
```
{static_info}

请提供：
1. 错误类型和根因分析
2. 具体的修复步骤
3. 预防建议

请用中文回答，格式如下：
修复建议: <具体命令或代码>
分析: <简要分析>
"""
        
        headers = {
            "Authorization": f"Bearer {self._config.api_key}",
            "Content-Type": "application/json",
        }
        
        payload = {
            "model": self._config.model,
            "messages": [
                {"role": "system", "content": "你是一个专业的代码调试助手，擅长分析错误并提供修复方案。"},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.3,
            "max_tokens": 1500,
        }
        
        api_base = self._config.api_base or "https://api.openai.com/v1"
        endpoint = f"{api_base.rstrip('/')}/chat/completions"
        
        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.post(endpoint, headers=headers, json=payload)
            response.raise_for_status()
            result = response.json()
            llm_response = result["choices"][0]["message"]["content"]
        
        # 提取修复建议
        import re
        fix_match = re.search(r"修复建议[：:]\s*(.+?)(?:\n|$)", llm_response, re.DOTALL)
        fix_suggestion = fix_match.group(1).strip() if fix_match else None
        
        return {
            "fix_suggestion": fix_suggestion,
            "explanation": llm_response,
        }
    except Exception as e:
        logger.error(f"LLM 分析失败: {e}")
        return {
            "fix_suggestion": None,
            "explanation": f"分析失败: {str(e)}",
        }
